### ISSUE TITLE
IntHashSet & IntIntHashTable dont compile to Java

### ISSUE THREAD

**Issue by mreshet** [polygonal/ds#18]
It looks like NULLs are being assigned to Int variables.   In the meantime, I'll have to use the standard Haxe Map<K, V> - all the HashTable implementations seem in Polygonal DS seem to rely on IntHashSet, IntHashTable or IntHashTable which do not compile when targeting Java or other "static" languages.

polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:761: characters 11-42 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:762: characters 11-37 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:823: characters 21-44 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:917: characters 24-48 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:920: characters 24-53 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:1016: characters 23-41 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:1017: characters 10-34 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:196: characters 10-36 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:198: characters 10-41 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntHashSet.hx:199: characters 10-36 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:717: characters 21-44 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1333: characters 11-41 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1334: characters 11-37 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1394: characters 21-44 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1489: characters 24-48 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1492: characters 24-53 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1591: characters 23-41 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:1592: characters 10-34 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:215: characters 10-36 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:217: characters 10-40 : On static platforms, null can't be used as basic type Int
polygonal-ds/1,4,1/de/polygonal/ds/IntIntHashTable.hx:219: characters 10-36 : On static platforms, null can't be used as basic type Int

**Comment by mirraraenn** [comment]
This seems more like an issue for all static platforms as indicated by the error. I also still experience this error for C# targets (another static compile target) as of Haxe 3.1.3 and Polygonal-DS 1.4.1

**Comment by polygonal** [comment]
Please test with latest version from git

**Comment by polygonal** [comment]
Compilation fails at this line in IntIntHashTable.hx:
```
class IntIntHashTableKeyIterator implements de.polygonal.ds.Itr<Int>
```
Error:
```
src\de\polygonal\ds\IntIntHashTableValIterator.java:7: error: IntIntHashTableValIterator is not abstract and does not override abstract method next() in Itr
public class IntIntHashTableValIterator extends haxe.lang.HxObject implements de.polygonal.ds.Itr<java.lang.Object>
       ^
src\de\polygonal\ds\IntIntHashTableValIterator.java:89: error: next() in IntIntHashTableValIterator cannot implement next() in Itr
        public int next()
                   ^
  return type int is not compatible with Object
  where T is a type-variable:
    T extends Object declared in interface Itr
src\de\polygonal\ds\IntIntHashTableKeyIterator.java:7: error: IntIntHashTableKeyIterator is not abstract and does not override abstract method next() in Itr
```

**Comment by polygonal** [comment]
minified example that fails to compile:

```
interface A<T>
{
    function foo():T;
}

class B implements A<Int>
{
    public function new() {}
    
    public function foo():Int return 0;
}

class Test
{
    static function main() {}
}
```
Output:
haxelib run hxjava hxjava_build.txt --haxe-version 3201 --feature-level 1
C:\Program Files\java\jdk1.8.0_66\bin\javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
src\haxe\root\B.java:6: error: B is not abstract and does not override abstract method foo() in A
public class B extends haxe.lang.HxObject implements haxe.root.A<java.lang.Object>
       ^
src\haxe\root\B.java:39: error: foo() in B cannot implement foo() in A
        public int foo()
                   ^
  return type int is not compatible with Object
  where T is a type-variable:
    T extends Object declared in interface A
```
