### ISSUE TITLE
Array2 not working using haxe 3.2.0-rc2

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [polygonal/ds#25]
This code:

```
class Test {
  static function main() : Void {
    var x : de.polygonal.ds.Array2<Int> = new de.polygonal.ds.Array2(10,10);
    x.set(0,0,3);
    trace(x.get(0,0));
  }
}
```

outputs:

```
Test.hx:5: 0
```

(which is incorrect).

This happens with haxe 3.2.0-rc2 on linux64. haxe 3.1.3 is fine.

**Comment by Simn** [comment]
If this indeed changed between Haxe versions there's a chance it was introduced by a Haxe bug.

**Comment by polygonal** [comment]
Seems there is a problem with inlining when compiling with -cpp, other targets work. Work when using --no-inline directive.

**Comment by Simn** [comment]
Could you check with current development version of Haxe? I've made some inlining fixes recently.

**Comment by polygonal** [comment]
Tested with Haxe Compiler 3.3.0 (git build development @ 066f0bf), still doesn't work (trace(x.get(0,0)) returns zero)

**Comment by Simn** [comment]
```
C:\Users\simn\Documents\TestMisc>haxe -main Main -cp src -cpp bin/cpp -lib polygonal-ds -lib polygonal-printf -cmd "c:\users\simn\documents\testmisc\bin\cpp\main.exe"
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.3" -Dhxcpp_api_level="321" -Dpolygonal-ds="0.0.0" -Dpolygonal-printf="1.0.2-beta" -Dpolygonal_ds="0.0.0" -Dpolygonal_printf="1.0.2-beta" -Dsource-header="Generated by Haxe" -I"C:\\GitHub\\haxe\\lib/polygonal-printf/1,0,2-beta/" -I"C:\\GitHub\\ds\\src\\" -I"src/" -I"C:\\GitHub\\haxe\\extraLibs/" -I"" -I"C:\\GitHub\\haxe\\std/cpp/_std/" -I"C:\\GitHub\\haxe\\std/"
Main.hx:5: 3
```

This almost certainly was an instance of https://github.com/HaxeFoundation/haxe/issues/1827. Can you double check that you're using the right executable and all?

**Comment by polygonal** [comment]
My official Haxe installation is in C:\HaxeToolkit\haxe; so I've downloaded the latest build from here: http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/ and extracted the contents into C:\HaxeToolkit\haxe_dev, then just compiled by pointing to this executable with C:\HaxeToolkit\haxe_dev\haxe.exe -cpp ... Is there anything else? I'm using hxcpp 3.2.205 btw.

**Comment by Simn** [comment]
That should be fine. What C compiler are you using? There's a possibility that we're relying on undefined order of operations somewhere.

I'm afraid someone has to figure out what exactly causes the problem here. I can't help much because it's working for me.

**Comment by polygonal** [comment]
I'm using MinGW. just tried MS VC but it doesn't solve the problem.

**Comment by polygonal** [comment]
Think I've found the problem.
This doesn't work:
Usage:
```
var foo = new Foo<Int>();
foo.set(10, 5);
trace(foo.get(10));
```
```
class Foo<T>
{
	var data = new haxe.ds.Vector<T>(100);
	
	public function new() {}
	inline public function get(i:Int) return data[i];
	inline public function set(i:Int, v:T) data[i] = v;
}
```
This works:
Usage:
```
var foo = new Foo();
foo.set(10, 5);
trace(foo.get(10));
```
```
class Foo
{
	var data = new haxe.ds.Vector<Int>(100);
	
	public function new() {}
	inline public function get(i:Int) return data[i];
	inline public function set(i:Int, v:Int) data[i] = v;
}
```
This also works:
Usage:
```
var foo = new Foo<Int>();
foo.set(10, 5);
trace(foo.get(10));
```
```
class Foo<T>
{
	var data = new Array<T>();
	
	public function new() {}
	inline public function get(i:Int) return data[i];
	inline public function set(i:Int, v:T) data[i] = v;
}
```

**Comment by polygonal** [comment]
I'm trying to find a workaround for now without rewriting much code so my idea was to typedef Vector<T> to another type for the cpp target but the code below doesn't work... any ideas?
```
abstract MockVector<T>(Array<T>)
{
	public inline function new(length:Int) untyped this = new Array<T>();
	@:arrayAccess public inline function get(index:Int):Null<T> return this[index];
	@:arrayAccess public inline function set(index:Int, val:T):T return this[index] = val;
}

typedef Vector<T> = MockVector<T>;

class Foo<T>
{
	var data = new Vector<T>(100);
	
	public function new() {}
	inline public function get(i:Int) return data[i];
	inline public function set(i:Int, v:T) data[i] = v;
}
```
Usage:
```
var foo = new Foo<Int>();
foo.set(10, 5);
trace(foo.get(10));
```

**Comment by Simn** [comment]
That's still the same original Array problem. I don't have a good solution for this at the moment, the only thing that works is having a custom `@:generic` class over Array like so:

```haxe
@:generic class MyArray<T> {
	var storage:Array<T>;
	public inline function new(length:Int) storage = new Array<T>();
	@:arrayAccess public inline function get(index:Int):Null<T> return storage[index];
	@:arrayAccess public inline function set(index:Int, val:T):T return storage[index] = val;
}

abstract MockVector<T>(MyArray<T>) {
	public inline function new(length:Int) this = new MyArray<T>(length);
	@:arrayAccess public inline function get(index:Int):Null<T> return this.get(index);
	@:arrayAccess public inline function set(index:Int, val:T):T return this.set(index, val);
}

typedef Vector<T> = MockVector<T>;

class Foo<T> {
	var data = new Vector<T>(100);

	public function new() {}
	inline public function get(i:Int) return data[i];
	inline public function set(i:Int, v:T) data[i] = v;
}

class Main {
	static function main() {
		var foo = new Foo<Int>();
		foo.set(10, 5);
		trace(foo.get(10));
	}
}
```

**Comment by polygonal** [comment]
All unit tests pass assuming it is compiled against the latest haxe nightly and hxcpp from git.. there are still some minor problems with inlining and -cpp (search the code for //#if !cpp inline #end)

**Comment by Simn** [comment]
Any details what's going wrong there? If this is a problem with Haxe I would very much like to fix it.

**Comment by polygonal** [comment]
See #30, hope it helps. Guess the other issues with inlining are also related to this.

**Comment by polygonal** [comment]
I've isolated the problem in #30
