### ISSUE TITLE
Graph/Graphnode

### ISSUE THREAD

**Issue by vantreeseba** [polygonal/ds#35]
When creating a graphnode, you have to supply a graph to it, but it does nothing but keep it internally.

Would this be better to do when adding it to the graph itself, or should it add itself to the graph at construction?

Currently the code looks like
```haxe
var graph = new Graph<MyData>();
var myData = new MyData();
var node = new GraphNode<MyData>(graph, myData);
graph.add(node);
```

I'm imagining it would be easier to understand if it was something like
```haxe
var graph  = new Graph<MyData>();
var myData = new MyData();
var node = new GraphNode<MyData>(myData);
graph.add(node); //this would set the graph var on the node.
```

or 

```haxe
var graph  = new Graph<MyData>();
var myData = new MyData();
var node = new GraphNode<MyData>(graph, myData);  //this would call graph.add.
```

The way its currently implemented doesn't seem clear, and I don't see what benefit it has.  I'll make a branch and PR if this sounds good.

**Comment by Glidias** [comment]
A bit nitpicky though, not too sure why he does it that way...maybe he had his reasons, though I did consider the second method as viable, the helper/factory method using graph.createNode() is better to be used instead to avoid having to supply the "graph" dependency.  Perhaps, there may have been semantic reasons why a GraphNode should be conventionally tied exclusively to it's Graph in a 1-to-1 relationship. Albeit, outside of this convention, I did consider the possiibility of a branch where one can add/transfer a node from/to multiple Graphs, with the possibiliity of using oldGraph.removeNode(node) before using newGraph.add(node) when using newGraph.addNode() (where it detected it belonged to another old graph earlier). 

Reason why graph.createNode() doesn't register the node but only acts only as a factory method is single responsibility principle. Also, i remembered he had various examples where that method was used as a factory method. Your 3rd approach violates single responsibility principle, and forces the graph to add the node within the constructor process when there may be some situations where adding the node to the graph might work better as a deferred process.

**Comment by polygonal** [comment]
createNode() creates a node that is *owned* by the graph. So calling `graph.createNode()` is more clear in my opinion than `new GraphNode<T>(graph, val)`. In fact I think that GraphNode constructor should be private this way. Otoh addNode() adds an existing graph node object, because nodes can be removed  from and re-added to the graph. Also, the node uses the graph reference for pooling arc nodes which is quite important when modifying the graph frequently.

**Comment by polygonal** [comment]
GraphNode&lt;T&gt; constructor is now just
```haxe
function new (val:T)
```
The graph reference (GraphNode.mGraph) is set or cleared when calling graph.addNode() or graph.removeNode(), respectively. Arcs can now only be added after adding a node object to a graph, but this should be the case anyway.

So the code looks now like this:
```haxe
var myNode = myGraph.addNode(new GraphNode<MyData>(new MyData()));
```

I've also added a helper function which does exactly the same:

```haxe
var myNode = myGraph.add(new MyData());
```
