### ISSUE TITLE
error when running tests

### ISSUE THREAD

**Issue by mboussaa** [polygonal/ds#36]
I got this error when running tests in java
root@***********:/shared/ds/test# haxe -cp src  -main UnitTest.hx -lib polygonal-ds -java target/cpp/
TestArray2.hx:3: characters 7-45 : Type not found : de.polygonal.ds.tools.NativeArrayTools
UnitTest.hx:3: lines 3-107 : Defined in this class
TestArray3.hx:5: characters 7-45 : Type not found : de.polygonal.ds.tools.NativeArrayTools
UnitTest.hx:3: lines 3-107 : Defined in this class
TestArrayedQueue.hx:3: characters 7-34 : Type not found : de.polygonal.ds.NativeArray
UnitTest.hx:3: lines 3-107 : Defined in this class
TestArrayList.hx:2: characters 7-32 : Type not found : de.polygonal.ds.ArrayList
UnitTest.hx:3: lines 3-107 : Defined in this class
TestArrayTools.hx:1: characters 10-42 : Type not found : de.polygonal.ds.tools.ArrayTools
UnitTest.hx:3: lines 3-107 : Defined in this class
/usr/lib/haxe/lib/polygonal-ds/1,4,1/de/polygonal/ds/Bits.hx:47: characters 40-41 : Missing ;

**Comment by mboussaa** [comment]
in fact tests do not work

**Comment by polygonal** [comment]
> /usr/lib/haxe/lib/polygonal-ds/1,4,1/de/polygonal/ds/Bits.hx:47

1.4.x is outdated, a new version will be uploaded to haxelib soon. also java is not supported right now.

**Comment by polygonal** [comment]
please try with 2.0-beta on haxelib
