### ISSUE TITLE
macro in 'ds/tools/Assert.hx' break old code

### ISSUE THREAD

**Issue by fnaith** [polygonal/ds#41]
'haxe.macro.PositionTools.toLocation' seems not exist.

Haxe: 3.7.4
Target: cs

**Comment by fnaith** [comment]
Sorry, I just find that README already said supported version is 4.0.0

**Comment by fnaith** [comment]
But it is still odd that you can build it with Haxe 3.4.5 .
Could you give some hint? Compile fail just for Assert is very depressing QwQ

**Comment by fnaith** [comment]
fortunately, Assert.hx remand as it modified before df31fc2 then remove "de" from 'pack' arguments.
It will make assert() works with Haxe 3.4.7 cs

**Comment by polygonal** [comment]
Due to lack of time I can't tes Haxe 3.x anymore. You can compile with -D no-assert to remove them altogether
